--- 
title: "NYC 2022 Shooting Incident Analysis"
author: "William Gu, Shujie Hu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

  The New York Police Department records reported crime and releases datasets related to police enforcement and criminal activity, aiming to increase transparency and foster collaboration. We are interested in the citywide crime statistics, specifically shooting incidents in 2022, because we want to explore the patterns of New York City’s shooting incidents to study perpetrator-victim relationships and address personal safety awareness. It is worth studying these up-to-date shooting incidents when living in NYC, thereby we can have a clear picture of the crimes around us to avoid possible dangers. Through various data visualization techniques, we hope to find out answers to the following questions that we are interested in studying:
1. The number of shooting incidents with respect to the time(month or hour in a day).
2. The number of shooting incidents with respect to the five boroughs(The Bronx, Brooklyn, Manhattan, Queens, and Staten Island)
3. Given that the shooting occurs, the probability of death with respect to the five boroughs.
4. Given that the shooting occurs, the probability of death with respect to the location of the shooting incident.
5. The visualization of the perpetrator’s characteristics (eg. age,  sex, and race) 
6. The visualization of the victim’s characteristics to figure out possible inclination.
7. The relationship between different boroughs and the perpetrator’s characteristics.
8. The relationship between different boroughs and the victim’s characteristics.
9. The probability of death with respect to the perpetrator’s age, sex, and race VS. the victim’s characteristics.
10. The probability of death in the shooting incidents with respect to hours in a day.

browseURL("docs/index.html")
