# Interactive component
In this part, we provides two interactive plots in order to further explore our data more conveniently.

In previous plots, we observed shooting incident weekly counts as the data appears narrowed for a large time range. In the first plot, we can use interactive tools to zoom in on selected time range, so that we can observe the day-to-day change of shooting incident numbers, and observe the overall trend at the same time.
```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(ggalluvial)
library(plotly)

data <- read.csv("./data/NYPD_Shooting_Incident_Data__Year_To_Date_.csv", na.strings=c("(null)", "UNKNOWN", "U"))

df_date <- data %>% mutate(OCCUR_DATE = as.Date(OCCUR_DATE, '%m/%d/%Y'))
#str(df_date)

#df_date2 <- df_date |> mutate(week = lubridate::week(df_date$OCCUR_DATE)) |> group_by(week) |> summarize(Count = n())
#df_date2 <- df_date2 |> mutate(Date= lubridate::ymd( "2022-01-01" ) + lubridate::weeks( df_date2$week - 1 ))
df_date <- df_date |> rename(Date=OCCUR_DATE) |> group_by(Date) |> summarize(Count = n())
#df_date2

plot_ly(  
    df_date, x = ~Date, y = ~Count, 
    type = 'scatter',  
    mode = 'lines+markers',  
    # Hover text:  
    hoverinfo = 'text',  
    text = ~paste(Date)  
)  
```
<br>
We can also explore the distribution of shooting incident at the time of day, with variation of victim's age range and within the selected window of dates. By using the slider in the second plot, we can change the range of month selected, thus we can observe the change in distribution. In the dropdown menu, we can select the age range of victim. It is set to 'All', which means all data were selected by default. By changing the selection, we can explore the distribution based on different victim characteristics; and we can set it back to default at any time. 
For instance, by selecting "65+" we can observe only a small amount of incidents happened and they all distributed in the evening, which are statistically understandable. 



<meta charset="utf-8">

<style>
svg {
    font-family: sans-serif;
}

rect.overlay {
    stroke: black;
}

rect.selection {
  stroke: none;
  fill: steelblue;
  fill-opacity: 0.6;
}

#labelleft, #labelright {
  dominant-baseline: hanging;
  font-size: 12px;
}

#labelleft {
    text-anchor: end;
}

#labelright {
    text-anchor: start;
}
</style>

<!-- Load d3.js you can use ither version if you want -->
<script src="https://d3js.org/d3.v4.js"></script>

<!-- Create a div where the graph will take place -->
<div id="sliderDiv"></div>
<p id="dropdownP" style="margin-left:100px;">Victim age range: </p>
<div id="dataviz"></div>

<script>

// set the dimensions and margins of the graph
// You can change these values these are just sample values given
var margin = {top: 30, right: 100, bottom: 60, left: 100},
    width = 800 - margin.left - margin.right,
    height = 600 - margin.top - margin.bottom;

// append the svg object to the body of the page
var svg = d3.select("#dataviz")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

var layout = ({width: 800, height: 100,
  margin: {top: 30, bottom: 35, left: 100, right: 100}
})

slider_snap = function(min, max, starting_min=min, starting_max=max) {
  var range = [min, max + 1]
  var starting_range = [starting_min, starting_max + 1]

  // set width and height of svg
  var w = layout.width
  var h = layout.height
  var margin = layout.margin

  // dimensions of slider bar
  var width = w - margin.left - margin.right;
  var height = h - margin.top - margin.bottom;

  // create x scale
  var x = d3.scaleLinear()
    .domain(range)  // data space
    .range([0, width]);  // display space
  
  // create svg and translated g
  var svg = d3.select("#sliderDiv").append("svg").attr("width", w).attr("height", h)
  const g = svg.append('g').attr('transform', `translate(${margin.left}, ${margin.top})`)
  
  // draw background lines
  g.append('g').selectAll('line')
    .data(d3.range(range[0], range[1]+1))
    .enter()
    .append('line')
    .attr('x1', d => x(d)).attr('x2', d => x(d))
    .attr('y1', 0).attr('y2', height)
    .style('stroke', '#ccc')
  
  // labels
  var labelL = g.append('text')
    .attr('id', 'labelleft')
    .attr('x', 0)
    .attr('y', height + 5)
    .text(range[0])

  var labelR = g.append('text')
    .attr('id', 'labelright')
    .attr('x', 0)
    .attr('y', height + 5)
    .text(range[1])

  // define brush
  var brush = d3.brushX()
    .extent([[0,0], [width, height]])
    .on('brush', function() {
      var s = d3.event.selection;
      // update and move labels
      labelL.attr('x', s[0])
        .text(Math.round(x.invert(s[0])))
      labelR.attr('x', s[1])
        .text(Math.round(x.invert(s[1])) - 1)
      // move brush handles      
      handle.attr("display", null).attr("transform", function(d, i) { return "translate(" + [ s[i], - height / 4] + ")"; });
      // update view
      // if the view should only be updated after brushing is over, 
      // move these two lines into the on('end') part below
      svg.node().value = s.map(d => Math.round(x.invert(d)));
      //svg.node().dispatchEvent(new CustomEvent("input"));
      let event = new Event("change"); sliderDiv.dispatchEvent(event);
    })
    .on('end', function() {
      if (!d3.event.sourceEvent) return;
      var d0 = d3.event.selection.map(x.invert);
      var d1 = d0.map(Math.round)
      d3.select(this).transition().call(d3.event.target.move, d1.map(x))
    })

  // append brush to g
  var gBrush = g.append("g")
      .attr("class", "brush")
      .call(brush)

  // add brush handles (from https://bl.ocks.org/Fil/2d43867ba1f36a05459c7113c7f6f98a)
  var brushResizePath = function(d) {
      var e = +(d.type == "e"),
          x = e ? 1 : -1,
          y = height / 2;
      return "M" + (.5 * x) + "," + y + "A6,6 0 0 " + e + " " + (6.5 * x) + "," + (y + 6) + "V" + (2 * y - 6) +
        "A6,6 0 0 " + e + " " + (.5 * x) + "," + (2 * y) + "Z" + "M" + (2.5 * x) + "," + (y + 8) + "V" + (2 * y - 8) +
        "M" + (4.5 * x) + "," + (y + 8) + "V" + (2 * y - 8);
  }

  var handle = gBrush.selectAll(".handle--custom")
    .data([{type: "w"}, {type: "e"}])
    .enter().append("path")
    .attr("class", "handle--custom")
    .attr("stroke", "#000")
    .attr("fill", '#eee')
    .attr("cursor", "ew-resize")
    .attr("d", brushResizePath);
    
  // override default behaviour - clicking outside of the selected area 
  // will select a small piece there rather than deselecting everything
  // https://bl.ocks.org/mbostock/6498000
  gBrush.selectAll(".overlay")
    .each(function(d) { d.type = "selection"; })
    .on("mousedown touchstart", brushcentered)
  
  function brushcentered() {
    var dx = x(1) - x(0), // Use a fixed width when recentering.
    cx = d3.mouse(this)[0],
    x0 = cx - dx / 2,
    x1 = cx + dx / 2;
    d3.select(this.parentNode).call(brush.move, x1 > width ? [width - dx, width] : x0 < 0 ? [0, dx] : [x0, x1]);
  }
  
  // select entire starting range
  gBrush.call(brush.move, starting_range.map(x))

  g.append("text")
    .attr("x", (width / 2))             
    .attr("y", 0 - (margin.top / 2))
    .attr("text-anchor", "middle")  
    .style("font-size", "16px") 
    //.style("text-decoration", "underline")  
    .text("Select time range");

  var getRange = function() { var range = d3.brushSelection(gBrush.node()).map(d => Math.round(x.invert(d))); return range }
  return {getRange: getRange}
  
  return svg.node()
}

// uncomment the function and complete this function to plot required graphs
d3.csv("https://raw.githubusercontent.com/tracyhsj/NYC2022-Shooting-Incident-Analysis/main/data/NYPD_Shooting_Incident_Data__Year_To_Date_.csv", function(data) {
  //console.log(data)

  var data_keys = ["All", "<18", "25-44", "18-24", "45-64", "65+"];

  var initial_key = "All"
  var curr_data = data;

  var dur = 500;

  // Y axis: initialization
  var y = d3.scaleLinear()
      .range([height, 0]);
  var yAxis = svg.append("g")

  var x = d3.scaleTime()
        .domain([new Date().setHours(0,0,0), new Date().setHours(23,59,59)])
        //.domain([format(timeparse("00:00:00")), format(timeparse("23:59:59"))])
        .range([0, width]);
  
  var xAxis = svg.append("g")
                .attr("transform", "translate(0," + height + ")")

  // A function that builds the graph for a specific value of bin
  function update() {
      xAxis
          .transition()
          .duration(dur)
          .call(d3.axisBottom(x));

    // set the parameters for the histogram
    var histogram = d3.histogram()
        .value(function(d) {
            const [hh, mm, ss] = d.OCCUR_TIME.split(':');
            return new Date().setHours(+hh, +mm, +ss);
            //return d.OCCUR_TIME;
            })   // I need to give the vector of value
        .domain(x.domain())  // then the domain of the graphic
        .thresholds(x.ticks(24)); // then the numbers of bins

    // And apply this function to data to get the bins
    var bins = histogram(curr_data);

    // Y axis: update now that we know the domain
    y.domain([0, d3.max(bins, function(d) { return d.length; })]);   // d3.hist has to be called before the Y axis obviously
    yAxis
        .transition()
        .duration(dur)
        .call(d3.axisLeft(y));

    // Join the rect with the bins data
    var u = svg.selectAll("rect")
        .data(bins)

    // Manage the existing bars and eventually the new ones:
    u
        .enter()
        .append("rect") // Add a new rect for each new elements
        .merge(u) // get the already existing elements as well
        .transition() // and apply changes to all of them
        .duration(dur)
          .attr("x", 1)
          .attr("transform", function(d) { return "translate(" + x(d.x0) + "," + y(d.length) + ")"; })
          .attr("width", function(d) { return x(d.x1) - x(d.x0) -1 ; })
          .attr("height", function(d) { return height - y(d.length); })
          .style("fill", "#69b3a2")

    // If less bar in the new histogram, I delete the ones not in use anymore
    u.exit().remove()

    };

    var dropdownChange = function() {
        var newKey = d3.select(this).property('value');
        if(newKey == "All") { curr_data = data;}
        else {curr_data = data.filter(d=>d.VIC_AGE_GROUP==newKey)}
        
        update();
        //console.log(curr_data)
        //update(parseInt(d3.select("#nBin").property('value')));
        //d3.select("#nBin").property('value', 10);
        //update(10);
    };

    var dropdown = d3.select("#dropdownP")
        .insert("select", "svg")
        .on("change", dropdownChange);

    dropdown.selectAll("option")
      .data(data_keys)
      .enter().append("option")
        .attr("value", function (d) { return d; })
        .text(function (d) {
            return d[0].toUpperCase() + d.slice(1,d.length); // capitalize 1st letter
        });

  update();

  var myslider = slider_snap(1, 12)

  d3.select('#sliderDiv').on('change', function() {
    //console.log(myslider.getRange())
    var starting_month = myslider.getRange()[0]
    var ending_month = myslider.getRange()[1]-1;
    curr_data = data.filter(function(d) {
      const [mm, dd, yy] = d.OCCUR_DATE.split('/')
      return parseInt(mm)>=starting_month && parseInt(mm)<=ending_month;
    })
    //console.log(starting_month, ending_month)
    //console.log(curr_data)
    update();
  });

  svg.append("text")
    .attr("class", "y label")
    .attr("text-anchor", "middle")
    .attr("y", -40)
    .attr("x", -height/2)
    .attr("transform", "rotate(-90)")
    .style("font-size", "16px")
    .text("Number of incidents");

  svg.append("text")
    .attr("x", (width / 2))             
    .attr("y", 0 - (margin.top / 2))
    .attr("text-anchor", "middle")  
    .style("font-size", "16px") 
    //.style("text-decoration", "underline")  
    .text("Shooting Incidents Occur time in 2022");


});
</script>
<!-- Reference: d3 slider codes: https://observablehq.com/@sarah37/snapping-range-slider-with-d3-brush-->